name: format-and-lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format-fish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install fish
        run: |
          sudo apt-get update
          sudo apt-get install -y fish
      - name: Check fish formatting
        run: ./scripts/format/fish.sh --check

  format-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install stylua
        uses: taiki-e/install-action@v2
        with:
          tool: stylua
      - name: Check lua formatting
        run: ./scripts/format/lua.sh --check

  format-toml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install taplo
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - name: Check toml formatting
        run: ./scripts/format/toml.sh --check

  format-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Check json formatting
        run: ./scripts/format/json.sh --check

  format-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt
      - name: Check shell formatting
        run: ./scripts/format/shell.sh --check

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shell lint
        run: |
          shellcheck -S error -s sh install.sh
          shellcheck -S error -s bash .zshenv .zprofile .zshrc
